# Generated by Django 3.2.5 on 2023-08-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210411_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
